[package]
name = "parley"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.19"
itertools = "0.10.3"
tokio = { version = "1.14.0", features = ["full"] }
